# Default values for selenium-node-firefox.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value
imageTag: 2.46.0
mem_limit: 512Mi
mem_request: 64Mi

SE_OPTS: -nodeConfig /var/selenium-config/config-firefox.json
HUB_PORT_4444_TCP_ADDR: selenium-hub
HUB_PORT_4444_TCP_PORT: 4444
