version: '2'

volumes:
    nginx_config:
      driver: local
      driver_opts:
        type: nfs
        o=addr: "${NFS_HOST},rw"
        device: /nfs/nginx_config
    nginx_releasenote:
      driver: local
      driver_opts:
        type: nfs
        o=addr: "${NFS_HOST},rw"
        device: /nfs/nginx_releasenote
    ldap_db:
      driver: local
      driver_opts:
        type: nfs
        o=addr: "${NFS_HOST},rw"
        device: /nfs/ldap_db
    ldap_static:
      driver: local
      driver_opts:
        type: nfs
        o=addr: "${NFS_HOST},rw"
        device: /nfs/ldap_static
    gerrit_mysql_data:
      driver: local
      driver_opts:
        type: nfs
        o=addr: "${NFS_HOST},rw"
        device: /nfs/gerrit_mysql_data
    git_repos:
      driver: local
      driver_opts:
        type: nfs
        o=addr: "${NFS_HOST},rw"
        device: /nfs/git_repos
    gerrit_review_site:
      driver: local
      driver_opts:
        type: nfs
        o=addr: "${NFS_HOST},rw"
        device: /nfs/gerrit_review_site
    sensu_api_conf:
      driver: local
      driver_opts:
        type: nfs
        o=addr: "${NFS_HOST},rw"
        device: /nfs/sensu_api_conf
    sensu_server_conf:
      driver: local
      driver_opts:
        type: nfs
        o=addr: "${NFS_HOST},rw"
        device: /nfs/sensu_server_conf
    sensu_client_conf:
      driver: local
      driver_opts:
        type: nfs
        o=addr: "${NFS_HOST},rw"
        device: /nfs/sensu_client_conf
    sensu_rabbitmq_data:
      driver: local
      driver_opts:
        type: nfs
        o=addr: "${NFS_HOST},rw"
        device: /nfs/sensu_rabbitmq_data
    sensu_redis_data:
      driver: local
      driver_opts:
        type: nfs
        o=addr: "${NFS_HOST},rw"
        device: /nfs/sensu_redis_data
    sonar_mysql_data:
      driver: local
      driver_opts:
        type: nfs
        o=addr: "${NFS_HOST},rw"
        device: /nfs/sonar_mysql_data
    sonar_data:
      driver: local
      driver_opts:
        type: nfs
        o=addr: "${NFS_HOST},rw"
        device: /nfs/sonar_data
    sonar_extensions:
      driver: local
      driver_opts:
        type: nfs
        o=addr: "${NFS_HOST},rw"
        device: /nfs/sonar_extensions
    sonar_logs:
      driver: local
      driver_opts:
        type: nfs
        o=addr: "${NFS_HOST},rw"
        device: /nfs/sonar_logs
    jenkins_home:
      driver: local
      driver_opts:
        type: nfs
        o=addr: "${NFS_HOST},rw"
        device: /nfs/jenkins_home
    jenkins_slave_home:
      driver: local
      driver_opts:
        type: nfs
        o=addr: "${NFS_HOST},rw"
        device: /nfs/jenkins_slave_home
    nexus_sonatype_work:
      driver: local
      driver_opts:
        type: nfs
        o=addr: "${NFS_HOST},rw"
        device: /nfs/nexus_sonatype_work
    registry_certs:
      driver: local
      driver_opts:
        type: nfs
        o=addr: "${NFS_HOST},rw"
        device: /nfs/registry_certs
    registry_data:
      driver: local
      driver_opts:
        type: nfs
        o=addr: "${NFS_HOST},rw"
        device: /nfs/registry_data
