proxy:
  volume_driver: nfs
  volumes:
    - /data/nginx_config:/etc/nginx
    - /data/nginx_releasenote:/usr/share/nginx/html

ldap:
  volume_driver: nfs
  volumes:
    - /data/ldap_db:/var/lib/ldap
    - /data/ldap_static:/etc/ldap

gerrit-mysql:
  volume_driver: nfs
  volumes:
    - /data/gerrit_mysql_data:/var/lib/mysql

gerrit:
  user: root
  volume_driver: nfs
  volumes:
    - /data/git_repos:/var/git/repos 
    - /data/gerrit_review_site:/var/gerrit/review_site 

sensu-api:
  volume_driver: nfs
  volumes:
    - /data/sensu_api_conf:/etc/sensu/conf.d

sensu-server:
  volume_driver: nfs
  volumes:
    - /data/sensu_server_conf:/etc/sensu/conf.d

sensu-client:
  volume_driver: nfs
  volumes:
    - /data/sensu_client_conf:/etc/sensu/conf.d

sensu-rabbitmq:
  volume_driver: nfs
  volumes:
    - /data/sensu_rabbitmq_data:/var/lib/rabbitmq

sensu-redis:
  volume_driver: nfs
  volumes:
    - /data/sensu_redis_data:/data

sonar-mysql:
  volume_driver: nfs
  volumes:
    - /data/sonar_mysql_data:/var/lib/mysql 

sonar:
  volume_driver: nfs
  volumes:
    - /data/sonar_data:/opt/sonarqube/data
    - /data/sonar_extensions:/opt/sonarqube/extensions
    - /data/sonar_logs:/opt/sonarqube/logs

jenkins:
  user: root 
  volume_driver: nfs
  volumes:
    - /data/jenkins_home:/var/jenkins_home 

selenium-node-chrome:
  volume_driver: nfs
  volumes:
    - /data/selenium_config:/var/selenium-config

selenium-node-firefox:
  volume_driver: nfs
  volumes:
    - /data/selenium_config:/var/selenium-config

nexus:
  volume_driver: nfs
  volumes:
    - /data/nexus_sonatype_work:/sonatype-work
