proxy:
  volume_driver: nfs
  volumes:
    - ${NFS_HOST}/nfs/nginx_config:/etc/nginx
    - ${NFS_HOST}/nfs/nginx_releasenote:/usr/share/nginx/html

ldap:
  volume_driver: nfs
  volumes:
    - ${NFS_HOST}/nfs/ldap_db:/var/lib/ldap
    - ${NFS_HOST}/nfs/ldap_static:/etc/ldap

gitlab-postgresql:
  volume_driver: nfs
  volumes:
    - ${NFS_HOST}/nfs/gitlab_postgresql_data:/var/lib/postgresql:rw

gitlab:
  volume_driver: nfs
  volumes:
    - ${NFS_HOST}/nfs/gitlab_config:/etc/gitlab:rw
    - ${NFS_HOST}/nfs/gitlab_logs:/var/log/gitlab:rw
    - ${NFS_HOST}/nfs/gitlab_data:/var/opt/gitlab:rw

gitlab-redis:
  volume_driver: nfs
  volumes:
    - ${NFS_HOST}/nfs/gitlab_redis_data:/data

sensu-api:
  volume_driver: nfs
  volumes:
    - ${NFS_HOST}/nfs/sensu_api_conf:/etc/sensu/conf.d

sensu-server:
  volume_driver: nfs
  volumes:
    - ${NFS_HOST}/nfs/sensu_server_conf:/etc/sensu/conf.d

sensu-client:
  volume_driver: nfs
  volumes:
    - ${NFS_HOST}/nfs/sensu_client_conf:/etc/sensu/conf.d

sensu-rabbitmq:
  volume_driver: nfs
  volumes:
    - ${NFS_HOST}/nfs/sensu_rabbitmq_data:/var/lib/rabbitmq

sensu-redis:
  volume_driver: nfs
  volumes:
    - ${NFS_HOST}/nfs/sensu_redis_data:/data

sonar-mysql:
  volume_driver: nfs
  volumes:
    - ${NFS_HOST}/nfs/sonar_mysql_data:/var/lib/mysql 

sonar:
  volume_driver: nfs
  volumes:
    - ${NFS_HOST}/nfs/sonar_data:/opt/sonarqube/data
    - ${NFS_HOST}/nfs/sonar_extensions:/opt/sonarqube/extensions
    - ${NFS_HOST}/nfs/sonar_logs:/opt/sonarqube/logs

jenkins:
  user: root 
  volume_driver: nfs
  volumes:
    - ${NFS_HOST}/nfs/jenkins_home:/var/jenkins_home 

selenium-node-chrome:
  volume_driver: nfs
  volumes:
    - ${NFS_HOST}/nfs/selenium_config:/var/selenium-config

selenium-node-firefox:
  volume_driver: nfs
  volumes:
    - ${NFS_HOST}/nfs/selenium_config:/var/selenium-config

nexus:
  volume_driver: nfs
  volumes:
    - ${NFS_HOST}/nfs/nexus_sonatype_work:/nexus-data

registry:
  volume_driver: nfs
  volumes:
    - ${NFS_HOST}/nfs/registry_certs:/certs
    - ${NFS_HOST}/nfs/registry_data:/data
