apiVersion: v1
kind: Service
metadata:
  name: sensu-api
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
spec:
  ports:
  - port: {{default 3306 .Values.apiPort}}
    targetPort: api
    protocol: TCP
    name: api
  selector:
    service: sensu-api
