apiVersion: v1
kind: Service
metadata:
  name: sensu-redis
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
spec:
  ports:
  - port: {{default 6379 .Values.clientPort}}
    targetPort: client
    protocol: TCP
    name: client
  selector:
    service: sensu-redis
