apiVersion: v1
kind: Service
metadata:
  name: gerrit-mysql
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
spec:
  ports:
  - port: {{default 3306 .Values.mysqlPort}}
    targetPort: mysql
    protocol: TCP
    name: mysql
  selector:
    service: gerrit-mysql
