apiVersion: v1
kind: Service
metadata:
  name: ldap
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
spec:
  ports:
  - port: {{default 389 .Values.ldapPort | quote }}
    targetPort: ldap
    protocol: TCP
    name: ldap
  selector:
    service: ldap
