apiVersion: v1
kind: Service
metadata:
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
  name: proxy
spec:
  type: {{default "ClusterIP" .Values.portType }}
  ports:
  - name: http
    port: {{default 80 .Values.httpPort | quote }}
    protocol: TCP
    targetPort: http
    {{if .Values.nodePort}}
    nodePort: {{.Values.nodePort | quote }}
    {{end}}
  - name: https
    port: {{default 443 .Values.httpsPort | quote }}
    protocol: TCP
    targetPort: https
  selector:
    service: proxy
