apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
  name: selenium-node-firefox
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: selenium-node-firefox
        release: {{.Release.Name | quote }}
    spec:
      containers:
      - env:
        - name: HUB_PORT_4444_TCP_ADDR
          value: "{{.Values.HUB_PORT_4444_TCP_ADDR}}"
        - name: HUB_PORT_4444_TCP_PORT
          value: "{{.Values.HUB_PORT_4444_TCP_PORT}}"
        - name: SE_OPTS
          value: "{{.Values.SE_OPTS}}"
        image: selenium/node-firefox:{{default "latest" .Values.imageTag}}
        name: selenium-node-firefox
        resources:
          limits:
            memory: "{{.Values.mem_limit}}"
          requests:
            memory: "{{.Values.mem_request}}"        
      restartPolicy: Always
