#!/bin/bash -e

SUB_CMD_NAME="letsencrypt"

cmd_desc() {
    echo "For running letsencrypt related commands"
}

cmd_usage() {
    echo "usage: ${CMD_NAME} ${SUB_CMD_NAME} <subcommand>"
    echo "subcommand:"
    printf "    %-12s   %s\n" "gen-certs" "Generate new ssl certificates for Nginx proxy."
    printf "    %-12s   %s\n" "export-certs" "Export new certificates from letsencrypr."
}

help() {
    echo
    echo "Available subcommands are:"
    printf "    %-22s   %s\n" "gen-certs" "Generate SSL certificates for Nginx ssl support"
    printf "    %-22s   %s\n" "export-certs" "Export new SSL certificates for Nginx proxy"
    printf "    %-22s   %s\n" "help" "Prints this help information"
    echo
}

prep_env() {
    source ${CONF_DIR}/env.config.sh
}

export-certs() {
    prep_env
    docker cp -L ${LE_CERT_PATH}/live/${REGISTRY_DOMAIN_NAME}/fullchain.pem proxy:/etc/nginx/ssl/
    docker cp -L ${LE_CERT_PATH}/live/${REGISTRY_DOMAIN_NAME}/privkey.pem proxy:/etc/nginx/ssl/
    docker exec proxy ln -s /etc/nginx/sites-available/registry.conf /etc/nginx/sites-enabled/registry.conf
    docker exec proxy nginx -s reload
}

gen-certs() {
    prep_env
    export REGISTRY_DOMAIN_NAME=$1
    
    if [ -z ${REGISTRY_DOMAIN_NAME} ]; then
         echo "
           Usage : 
             gen-certs <REGISTRY_DOMAIN_NAME>
           
           <REGISTRY_DOMAIN_NAME>: 
             This is the host which will secured by letsencript ssl.
               
           Examples: 
             gen-certs registry.example.com
         "
         exit 1
    fi

    echo "INFO: Will be requested new ssl certs for ${REGISTRY_DOMAIN_NAME}."

    docker run --rm --name letsencrypt -it -p 80:80 -p 443:443 -v ${LE_CERT_PATH}:/etc/letsencrypt accenture/letsencrypt certonly --standalone -d ${REGISTRY_DOMAIN_NAME} --text --register-unsafely-without-email --agree-tos

}

shift $(($OPTIND -1))
SUBCOMMAND_OPT="${1:-help}"

# Only shift if there are other parameters
if [ $# -ge 1 ]; then
    shift
fi

case ${SUBCOMMAND_OPT} in
    "cmd_desc"|"help"|"gen-certs"|"export-certs")
        ${SUBCOMMAND_OPT} "$@"
        ;;
    *)
        cmd_usage
        exit 1
        ;;
esac