#!/bin/bash -e

SUB_CMD_NAME="target"

cmd_desc() {
    echo "For setting up environment variables to connect with adop tools."
}

cmd_usage() {
    echo "usage: ${CMD_NAME} ${SUB_CMD_NAME} [<options>] <subcommand>"
    echo "Options:"
    printf "    %-12s   %s\n" "-t <endpoint>" "The endpoint url to connect to adop tool. (Required)"
    printf "    %-12s   %s\n" "-u <username>" "The username required for authentication with adop tool. (Required)"
    printf "    %-12s   %s\n" "-p <password>" "The password required for authentication with adop tool. (Required)"
}

help() {
    cmd_usage
    echo
    echo "Available subcommands are:"
    printf "    %-22s   %s\n" "help" "Prints this help information"
    printf "    %-22s   %s\n" "cmd_desc" "Prints this information about the subcommand."
    echo
}

# Parameters
while getopts "t:u:p:" opt; do
  case $opt in
    t)
      export ADOP_CLI_ENDPOINT=${OPTARG}
      ;;
    u)
      export ADOP_CLI_USER=${OPTARG}
      ;;
    p)
      export ADOP_CLI_PASSWORD=${OPTARG}
      ;;
    *)
      echo "Invalid parameter(s) or option(s)."
      cmd_usage
      exit 1
      ;;
  esac
done

if [ -z ${ADOP_CLI_ENDPOINT} ] | \
       [ -z ${ADOP_CLI_USER} ] | \
        [ -z ${ADOP_CLI_PASSWORD} ] ; then
    echo "ERROR : Required parameters are missing."
    help
    exit 1
else
    set +e
    URL_RC=$(curl -I -s -u ${ADOP_CLI_USER}:${ADOP_CLI_PASSWORD} ${ADOP_CLI_ENDPOINT})
    CMD_RC=$?
    set -e

    if [ ${CMD_RC} != 0 ] ; then
	echo "ENDPOINT ${ADOP_CLI_ENDPOINT} is invalid. Check the endpoint url."
    elif [ $(echo ${URL_RC} |head -n 1|cut -d$' ' -f2) != 200 ]; then
        echo "ENDPOINT ${ADOP_CLI_ENDPOINT} is inaccessible using CLI credentials ${ADOP_CLI_USER}:${ADOP_CLI_PASSWORD}. Check the endpoint and credentials"
    else
	mkdir -p $(pwd)/.adop
        echo "export ADOP_CLI_ENDPOINT=${ADOP_CLI_ENDPOINT}" > ${CLI_DIR}/.adop/target
        echo "export ADOP_CLI_USER=${ADOP_CLI_USER}" >> ${CLI_DIR}/.adop/target
        echo "export ADOP_CLI_PASSWORD=${ADOP_CLI_PASSWORD}" >> ${CLI_DIR}/.adop/target
        echo -e "To set the target for ADOP instance source following file -\n\t$(pwd)/.adop/target"
    fi
fi

shift $(($OPTIND -1))
SUBCOMMAND_OPT="${1}"

# Only shift if there are other parameters
if [ $# -ge 1 ]; then
    shift
fi

if [ ! -z ${SUBCOMMAND_OPT} ]; then
  case ${SUBCOMMAND_OPT} in
    "cmd_desc"|"help")
        ${SUBCOMMAND_OPT} "$@"
        ;;
    *)
        echo "Invalid subcommand : ${SUBCOMMAND_OPT}"
        help
        exit 1
        ;;
  esac
fi
