apiVersion: v1
kind: Service
metadata:
  name: nexus
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
spec:
  ports:
  - port: {{default 80 .Values.httpPort}}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    service: nexus
