# Default values for sonar.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value
imageTag: latest
httpPort: 9000
mem_limit: 512Mi
mem_request: 64Mi

LDAP_URL: ldap://ldap:389
LDAP_BIND_DN: cn=admin,dc=ldap,dc=example,dc=com
LDAP_BIND_PASSWORD: Jpk66g63ZifGYIcShSGM
LDAP_USER_BASE_DN: ou=people,dc=ldap,dc=example,dc=com
LDAP_USER_REQUEST: (&(objectClass=inetOrgPerson)(uid={login}))
LDAP_USER_REAL_NAME_ATTRIBUTE: displayName
LDAP_USER_EMAIL_ATTRIBUTE: mail
LDAP_GROUP_BASE_DN: ou=groups,dc=ldap,dc=example,dc=com
LDAP_GROUP_REQUEST: (&(objectClass=groupOfUniqueNames)(uniqueMember={dn}))
LDAP_GROUP_ID_ATTRIBUTE: cn
SONARQUBE_JDBC_URL: jdbc:mysql://sonar-mysql:3306/sonar?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true
