apiVersion: v1
kind: Service
metadata:
  name: selenium-hub
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
spec:
  ports:
  - port: {{default 4444 .Values.hubPort}}
    targetPort: hub
    protocol: TCP
    name: hub
  selector:
    service: selenium-hub
