apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
  name: sensu-uchiwa
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: sensu-uchiwa
        release: {{.Release.Name | quote }}
    spec:
      containers:
      - env:
        - name: SENSU_DC_NAME
          value: "{{.Values.SENSU_DC_NAME}}"
        - name: SENSU_HOSTNAME
          value: "{{.Values.SENSU_HOSTNAME}}"
        image: sstarcher/uchiwa:{{default "latest" .Values.imageTag}}
        name: sensu-uchiwa
        ports:
          - name: http
            containerPort: 3000
      restartPolicy: Always
