version: '2'

volumes:
    nginx_config:
      driver: local
    nginx_releasenote:
      driver: local
    ldap_db:
      driver: local
    ldap_static:
      driver: local
    gerrit_mysql_data:
      driver: local
    git_repos:
      driver: local
    gerrit_review_site:
      driver: local
    sensu_api_conf:
      driver: local
    sensu_server_conf:
      driver: local
    sensu_client_conf:
      driver: local
    sensu_rabbitmq_data:
      driver: local
    sensu_redis_data:
      driver: local
    sonar_mysql_data:
      driver: local
    sonar_data:
      driver: local
    sonar_extensions:
      driver: local
    sonar_logs:
      driver: local
    jenkins_home:
      driver: local
    jenkins_slave_home:
      driver: local
    nexus_sonatype_work:
      driver: local
    registry_certs:
      driver: local
    registry_data:
      driver: local
